import nodemailer from 'nodemailer';

// --- CONFIGURATION ---
// You need to enable "App Passwords" in your Google Account for this to work.
// Guide: https://support.google.com/accounts/answer/185833
const SMTP_EMAIL = process.env.SMTP_EMAIL;
const SMTP_PASSWORD = process.env.SMTP_PASSWORD;

const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: SMTP_EMAIL,
        pass: SMTP_PASSWORD,
    },
});

export async function sendEmail(to: string, subject: string, bodyHtml: string) {
    if (!SMTP_EMAIL || !SMTP_PASSWORD) {
        console.log("⚠️ Email Skipped: SMTP Credentials missing in .env.local");
        return;
    }

    try {
        const info = await transporter.sendMail({
            from: `"Smart Grid System" <${SMTP_EMAIL}>`,
            to: to,
            subject: subject,
            html: bodyHtml,
        });
        console.log("📧 Email sent: %s", info.messageId);
        return true;
    } catch (error) {
        console.error("❌ Email Error:", error);
        return false;
    }
}

// TEMPLATES
export const BILL_TEMPLATE = (amount: number, month: string) => `
  <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
    <h2 style="color: #2563EB;">⚡ Monthly Utility Bill</h2>
    <p>Hello Tenant,</p>
    <p>Your shared utility bill for <strong>${month}</strong> has been generated.</p>
    
    <div style="background: #f3f4f6; padding: 15px; border-radius: 5px; margin: 20px 0;">
      <h3 style="margin: 0; color: #333;">Amount Due: ₹ ${amount}</h3>
    </div>

    <p>Please pay via the dashboard or directly to the owner.</p>
    <br/>
    <p style="font-size: 12px; color: #888;">Auto-generated by Smart Meter System</p>
  </div>
`;
