"use client";

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { db } from '@/lib/firebase';
import { ref, onValue } from 'firebase/database';
import { Zap, Wifi, Clock, LogOut } from 'lucide-react';
import { Card, CardContent } from "@/components/ui/card";

export default function TenantDashboard() {
    const router = useRouter();
    const [houseId, setHouseId] = useState('');
    const [tenantName, setTenantName] = useState('');
    const [systemData, setSystemData] = useState<any>(null);

    useEffect(() => {
        // AUTH CHECK
        if (typeof window === 'undefined') return;
        const hid = sessionStorage.getItem('active_house_id');
        const role = sessionStorage.getItem('role');
        const tName = sessionStorage.getItem('tenant_name');

        if (!hid || role !== 'TENANT') {
            router.push('/login');
            return;
        }
        setHouseId(hid);
        setTenantName(tName || 'Tenant');

        // LIVE DATA FETCH
        const dataRef = ref(db, `houses/${hid}/system_status`);
        const unsub = onValue(dataRef, (snapshot) => {
            if (snapshot.exists()) setSystemData(snapshot.val());
        });

        return () => unsub();
    }, [router]);

    const handleLogout = () => {
        sessionStorage.clear();
        router.push('/login');
    };

    return (
        <div className="min-h-screen bg-slate-50 font-sans pb-20">
            {/* HEADER */}
            <header className="bg-white p-4 shadow-sm flex justify-between items-center sticky top-0 z-10">
                <div className="flex items-center gap-2">
                    <div className="bg-orange-100 p-2 rounded-full"><Zap className="h-5 w-5 text-orange-600" /></div>
                    <div>
                        <h1 className="font-bold text-slate-800 text-sm">Tenant Portal</h1>
                        <p className="text-xs text-slate-500">{houseId} • {tenantName}</p>
                    </div>
                </div>
                <button onClick={handleLogout} className="text-slate-400 hover:text-red-500"><LogOut className="h-5 w-5" /></button>
            </header>

            <main className="p-4 space-y-4">
                {/* LIVE CARD */}
                <Card className="bg-gradient-to-br from-blue-600 to-blue-800 text-white border-none shadow-lg">
                    <CardContent className="p-6">
                        <div className="flex justify-between items-start mb-4">
                            <div className="flex items-center gap-2 opacity-80 text-xs font-mono">
                                <Wifi className="h-3 w-3 animate-pulse" /> LIVE STATUS
                            </div>
                            <div className="text-xs bg-white/20 px-2 py-1 rounded">Today</div>
                        </div>

                        <div className="flex items-end gap-1 mb-1">
                            <span className="text-5xl font-bold tracking-tighter">{systemData?.voltage || 0}</span>
                            <span className="text-xl mb-1 opacity-80">V</span>
                        </div>
                        <p className="text-sm opacity-70">Current Voltage</p>

                        <div className="grid grid-cols-2 gap-4 mt-6 pt-6 border-t border-white/10">
                            <div>
                                <div className="text-2xl font-bold">{systemData?.current || 0} A</div>
                                <div className="text-xs opacity-60">Load Current</div>
                            </div>
                            <div>
                                <div className="text-2xl font-bold">{systemData?.today_runtime_hours || 0}h</div>
                                <div className="text-xs opacity-60">Usage Today</div>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                {/* INFO */}
                <div className="bg-white p-4 rounded-xl border shadow-sm">
                    <h3 className="font-bold text-slate-800 mb-2 flex items-center gap-2"><Clock className="h-4 w-4 text-slate-500" /> Billing Cycle</h3>
                    <p className="text-sm text-slate-600 mb-2">The next bill will be generated by the owner at the end of the month.</p>
                    <div className="p-3 bg-yellow-50 text-yellow-800 text-xs rounded border border-yellow-100">
                        ⚠️ Ensure your dues are cleared within 5 days of bill generation.
                    </div>
                </div>
            </main>
        </div>
    );
}
